var config={apiKey:"AIzaSyANKO5LqddgASdkSG2WzcPXLPQ41AkewPo",authDomain:"webd-portfolio-show-2017.firebaseapp.com",databaseURL:"https://webd-portfolio-show-2017.firebaseio.com",storageBucket:"webd-portfolio-show-2017.appspot.com",messagingSenderId:"888183054325"};var firebaseApp=firebase.initializeApp(config)
var db=firebaseApp.database()
var data=[]
firebase.database().ref('users').orderByChild("lastName").on('child_added',function(snapshot){data.push(snapshot.val())});console.log(data);var vm=new Vue({el:"#people",data:{items:data},methods:{intiSlider:initSlider},updated(){initSlider()}});function initSlider(){console.log("Test")
$('.swiper-container').css('opacity','1')
var firstSlide=Math.floor(Math.random()*17)
var mq=window.matchMedia("(min-width: 900px)");if(mq.matches){var thumbnailSlider=new Swiper('.thumbnails',{loop:!0,loopedSlides:18,initialSlide:firstSlide,slidesOffsetBefore:200,slidesPerView:'auto',slideToClickedSlide:!0,speed:1200,freeMode:!0,freeModeSticky:!0,slideActiveClass:'thumb-active',});var mainSlider=new Swiper('.main-slider',{loop:!0,loopedSlides:18,initialSlide:firstSlide,keyboardControl:!1,speed:1200,})}else{var thumbnailSlider=new Swiper('.thumbnails',{loop:!0,loopedSlides:18,initialSlide:firstSlide,centeredSlides:!0,slidesPerView:'auto',slideToClickedSlide:!0,speed:1200,freeMode:!0,freeModeSticky:!0,slideActiveClass:'thumb-active',});var mainSlider=new Swiper('.main-slider',{loop:!0,loopedSlides:18,initialSlide:firstSlide,keyboardControl:!1,speed:1200,})}
thumbnailSlider.params.control=mainSlider;mainSlider.params.control=thumbnailSlider}
$('section').horizon({swipe:!1});var aChildren=$("nav li").children().not('.eventbrite-link');var aArray=[];for(var i=0;i<aChildren.length;i++){var aChild=aChildren[i];var ahref=$(aChild).attr('href');aArray.push(ahref)}
$(window).scroll(function(){var windowPos=$(window).scrollLeft();var windowWidth=$(window).width();var docWidth=$(document).width();for(var i=0;i<aArray.length;i++){var theID=aArray[i];var divPos=$(theID).offset().left;var divWidth=$(theID).width();if(windowPos>=divPos&&windowPos<(divPos+divWidth)){$("a[href='"+theID+"']").parent().addClass("selected");console.log(theID)}else{$("a[href='"+theID+"']").parent().removeClass("selected")}}
if(window.location.href.indexOf("#home")!=-1){$("header > a").fadeTo('fast',0)}else{$("header > a").fadeTo('fast',1)}
if(windowPos+windowWidth==docWidth){if(!$("nav li:last-child a").hasClass("selected")){var navActiveCurrent=$(".selected").attr("href");$("a[href='"+navActiveCurrent+"']").removeClass("selected");$("nav li:last-child a").addClass("selected")}}});neededkeys=[38,38,40,40,37,39,37,39,66,65],started=!1,count=0;$(document).keydown(function(e){key=e.keyCode;if(!started){if(key==38){started=!0}}
if(started){if(neededkeys[count]==key){count++}else{reset()}
if(count==10){var audio=new Audio('SnapSnapClap.mp3');audio.play();reset()}}else{reset()}});function reset(){started=!1;count=0;return}